import {
  Users,
  Wallet,
  ShieldCheck,
  TrendingUp,
  LayoutDashboard,
  CreditCard,
  History,
  Calendar,
  Settings,
  LogOut,
  ChevronRight,
  ArrowUpRight,
  CheckCircle2,
  Clock,
  Bell,
  Plus,
  ArrowDownToLine,
  MoreVertical,
  Search,
  Link2, Zap, Activity, Crosshair, Megaphone, Target, Check, TriangleAlert,
  PiggyBank,
  BookOpen,
  MessageCircle,
  HelpCircle,
  Upload,
  Eye,
  MessageSquare,
  X,
  ArrowRight,
  Award,
  PieChart,
  Save,
  AlertCircle,
  AlertTriangle
} from "lucide-react";


export const Icons = {
  Users,
  Wallet,
  ShieldCheck,
  TrendingUp,
  LayoutDashboard,
  CreditCard,
  History,
  Calendar,
  Settings,
  LogOut,
  ChevronRight,
  ArrowUpRight,
  CheckCircle2,
  Clock,
  Bell,
  Plus,
  ArrowDownToLine,
  MoreVertical,
  Search,
  Link2, Zap, Activity, Crosshair, Megaphone, Target, Check, TriangleAlert, MessageSquare,
  PiggyBank,
  BookOpen,
  MessageCircle,
  HelpCircle,
  Upload,
  Eye,
  X,
  ArrowRight,
  Award,
  PieChart,
  Save,
  AlertCircle,
  AlertTriangle
} as const;
