/**
 * African nationalities (demonyms) for the beneficial-owner nationality
 * selector on employer onboarding. Covers all 54 UN-recognised African states,
 * sorted alphabetically. Common/widely-recognised English demonym forms are
 * used for the irregular ones (e.g. Lesotho → Basotho, Botswana → Motswana).
 */
export const AFRICAN_NATIONALITIES: readonly string[] = [
  'Algerian',
  'Angolan',
  'Basotho', // Lesotho
  'Beninese',
  'Bissau-Guinean',
  'Botswanan',
  'Burkinabé',
  'Burundian',
  'Cabo Verdean',
  'Cameroonian',
  'Central African',
  'Chadian',
  'Comoran',
  'Congolese', // Republic of the Congo
  'Congolese (DRC)',
  'Djiboutian',
  'Egyptian',
  'Equatorial Guinean',
  'Eritrean',
  'Eswatini',
  'Ethiopian',
  'Gabonese',
  'Gambian',
  'Ghanaian',
  'Guinean',
  'Ivorian',
  'Kenyan',
  'Liberian',
  'Libyan',
  'Malagasy',
  'Malawian',
  'Malian',
  'Mauritanian',
  'Mauritian',
  'Moroccan',
  'Mozambican',
  'Namibian',
  'Nigerian',
  'Nigerien',
  'Rwandan',
  'Sao Tomean',
  'Senegalese',
  'Seychellois',
  'Sierra Leonean',
  'Somali',
  'South African',
  'South Sudanese',
  'Sudanese',
  'Tanzanian',
  'Togolese',
  'Tunisian',
  'Ugandan',
  'Zambian',
  'Zimbabwean',
] as const;
