
insert into public.payout_providers (country_code, provider_key, provider_name, method_type) values
  ('KE', 'mpesa', 'M-PESA', 'mobile_money'),
  ('KE', 'airtel', 'Airtel Money', 'mobile_money'),
  ('UG', 'mtn', 'MTN Mobile Money', 'mobile_money'),
  ('UG', 'airtel', 'Airtel Money', 'mobile_money'),
  ('TZ', 'mpesa', 'M-Pesa Tanzania', 'mobile_money'),
  ('TZ', 'airtel', 'Airtel Money', 'mobile_money'),
  ('TZ', 'tigo', 'Tigo Pesa', 'mobile_money'),
  ('RW', 'mtn', 'MTN MoMo', 'mobile_money'),
  ('RW', 'airtel', 'Airtel Money', 'mobile_money'),
  ('KE', 'absa_ke', 'Absa Bank Kenya', 'bank_transfer'),
  ('KE', 'access_ke', 'Access Bank Kenya', 'bank_transfer'),
  ('KE', 'abc_ke', 'African Banking Corporation', 'bank_transfer'),
  ('KE', 'boa_ke', 'Bank of Africa Kenya', 'bank_transfer'),
  ('KE', 'baroda_ke', 'Bank of Baroda Kenya', 'bank_transfer'),
  ('KE', 'boi_ke', 'Bank of India Kenya', 'bank_transfer'),
  ('KE', 'citi_ke', 'Citibank N.A. Kenya', 'bank_transfer'),
  ('KE', 'cib_ke', 'Commercial International Bank (CIB)', 'bank_transfer'),
  ('KE', 'coop_ke', 'Co-operative Bank of Kenya', 'bank_transfer'),
  ('KE', 'credit_ke', 'Credit Bank', 'bank_transfer'),
  ('KE', 'dtb_ke', 'Diamond Trust Bank (DTB)', 'bank_transfer'),
  ('KE', 'ecobank_ke', 'Ecobank Kenya', 'bank_transfer'),
  ('KE', 'equity_ke', 'Equity Bank Kenya', 'bank_transfer'),
  ('KE', 'family_ke', 'Family Bank', 'bank_transfer'),
  ('KE', 'fcb_ke', 'First Community Bank', 'bank_transfer'),
  ('KE', 'gulf_ke', 'Gulf African Bank', 'bank_transfer'),
  ('KE', 'hfc_ke', 'Housing Finance Company', 'bank_transfer'),
  ('KE', 'im_ke', 'I&M Bank Kenya', 'bank_transfer'),
  ('KE', 'kcb_ke', 'KCB Bank Kenya', 'bank_transfer'),
  ('KE', 'meb_ke', 'Middle East Bank Kenya', 'bank_transfer'),
  ('KE', 'ncba_ke', 'NCBA Bank Kenya', 'bank_transfer'),
  ('KE', 'prime_ke', 'Prime Bank', 'bank_transfer'),
  ('KE', 'sbm_ke', 'SBM Bank Kenya', 'bank_transfer'),
  ('KE', 'stanbic_ke', 'Stanbic Bank Kenya', 'bank_transfer'),
  ('KE', 'scb_ke', 'Standard Chartered Kenya', 'bank_transfer'),
  ('KE', 'uba_ke', 'UBA Kenya', 'bank_transfer'),
  ('KE', 'victoria_ke', 'Victoria Commercial Bank', 'bank_transfer'),
  ('KE', 'zenith_ke', 'Zenith Bank Kenya', 'bank_transfer'),
  ('TZ', 'crdb_tz', 'CRDB Bank', 'bank_transfer'),
  ('TZ', 'nmb_tz', 'NMB Bank', 'bank_transfer'),
  ('TZ', 'nbc_tz', 'NBC Bank', 'bank_transfer'),
  ('TZ', 'absa_tz', 'Absa Bank Tanzania', 'bank_transfer'),
  ('TZ', 'stanbic_tz', 'Stanbic Bank Tanzania', 'bank_transfer'),
  ('TZ', 'scb_tz', 'Standard Chartered Tanzania', 'bank_transfer'),
  ('TZ', 'citi_tz', 'Citibank Tanzania', 'bank_transfer'),
  ('TZ', 'dtb_tz', 'Diamond Trust Bank Tanzania', 'bank_transfer'),
  ('TZ', 'ecobank_tz', 'Ecobank Tanzania', 'bank_transfer'),
  ('TZ', 'exim_tz', 'Exim Bank Tanzania', 'bank_transfer'),
  ('TZ', 'kcb_tz', 'KCB Bank Tanzania', 'bank_transfer'),
  ('TZ', 'boa_tz', 'Bank of Africa Tanzania', 'bank_transfer'),
  ('TZ', 'access_tz', 'Access Bank Tanzania', 'bank_transfer'),
  ('TZ', 'equity_tz', 'Equity Bank Tanzania', 'bank_transfer'),
  ('TZ', 'im_tz', 'I&M Bank Tanzania', 'bank_transfer'),
  ('TZ', 'boi_tz', 'Bank of India Tanzania', 'bank_transfer'),
  ('TZ', 'uba_tz', 'United Bank for Africa Tanzania', 'bank_transfer'),
  ('TZ', 'mkombozi_tz', 'Mkombozi Commercial Bank', 'bank_transfer'),
  ('TZ', 'dcb_tz', 'DCB Commercial Bank', 'bank_transfer'),
  ('TZ', 'azania_tz', 'Azania Bank', 'bank_transfer'),
  ('UG', 'absa_ug', 'Absa Bank Uganda', 'bank_transfer'),
  ('UG', 'access_ug', 'Access Bank Uganda', 'bank_transfer'),
  ('UG', 'boa_ug', 'Bank of Africa Uganda', 'bank_transfer'),
  ('UG', 'baroda_ug', 'Bank of Baroda Uganda', 'bank_transfer'),
  ('UG', 'boi_ug', 'Bank of India Uganda', 'bank_transfer'),
  ('UG', 'cairo_ug', 'Cairo Bank Uganda', 'bank_transfer'),
  ('UG', 'centenary_ug', 'Centenary Bank', 'bank_transfer'),
  ('UG', 'citi_ug', 'Citibank Uganda', 'bank_transfer'),
  ('UG', 'dfcu_ug', 'DFCU Bank', 'bank_transfer'),
  ('UG', 'dtb_ug', 'Diamond Trust Bank Uganda', 'bank_transfer'),
  ('UG', 'ecobank_ug', 'Ecobank Uganda', 'bank_transfer'),
  ('UG', 'equity_ug', 'Equity Bank Uganda', 'bank_transfer'),
  ('UG', 'exim_ug', 'Exim Bank Uganda', 'bank_transfer'),
  ('UG', 'hfb_ug', 'Housing Finance Bank', 'bank_transfer'),
  ('UG', 'im_ug', 'I&M Bank Uganda', 'bank_transfer'),
  ('UG', 'kcb_ug', 'KCB Bank Uganda', 'bank_transfer'),
  ('UG', 'ncba_ug', 'NCBA Bank Uganda', 'bank_transfer'),
  ('UG', 'postbank_ug', 'PostBank Uganda', 'bank_transfer'),
  ('UG', 'salaam_ug', 'Salaam Bank Uganda', 'bank_transfer'),
  ('UG', 'stanbic_ug', 'Stanbic Bank Uganda', 'bank_transfer'),
  ('UG', 'scb_ug', 'Standard Chartered Uganda', 'bank_transfer'),
  ('UG', 'tropical_ug', 'Tropical Bank', 'bank_transfer'),
  ('UG', 'uba_ug', 'United Bank for Africa Uganda', 'bank_transfer'),
  ('RW', 'bok_rw', 'Bank of Kigali', 'bank_transfer'),
  ('RW', 'bpr_rw', 'BPR Bank Rwanda', 'bank_transfer'),
  ('RW', 'im_rw', 'I&M Bank Rwanda', 'bank_transfer'),
  ('RW', 'ecobank_rw', 'Ecobank Rwanda', 'bank_transfer'),
  ('RW', 'gtbank_rw', 'GT Bank Rwanda', 'bank_transfer'),
  ('RW', 'equity_rw', 'Equity Bank Rwanda', 'bank_transfer'),
  ('RW', 'ncba_rw', 'NCBA Rwanda', 'bank_transfer'),
  ('RW', 'access_rw', 'Access Bank Rwanda', 'bank_transfer'),
  ('RW', 'boa_rw', 'Bank of Africa Rwanda', 'bank_transfer'),
  ('RW', 'kcb_rw', 'KCB Bank Rwanda', 'bank_transfer'),
  ('RW', 'urwego_rw', 'Urwego Bank', 'bank_transfer'),
  ('RW', 'ab_rw', 'AB Bank Rwanda', 'bank_transfer'),
  ('RW', 'cogebanque_rw', 'Cogebanque', 'bank_transfer'),
  ('RW', 'zigama_rw', 'Zigama CSS', 'bank_transfer'),
  ('RW', 'brd_rw', 'Development Bank of Rwanda (BRD)', 'bank_transfer'),
  ('RW', 'unguka_rw', 'Unguka Bank', 'bank_transfer')
on conflict do nothing;

